### ISSUE TITLE
run-app fails using Tomcat 8 with JNDI resources

### ISSUE THREAD

**Issue by joosth** [grails-plugins/grails-tomcat-plugin#14]
Run-app fails on Tomcat8 when JNDI resources are defined in Config.groovy (`grails.naming.entries`) with the message below.
It appears InlineExplodedTomcatServer.groovy tries to load a `org.apache.catalina.deploy.ContextResource` (in line 191) which is nowhere to be found in Tomcat 8.
The problem does not occur using Tomcat 7 in which this class is present. 

The stacktrace is:

> | Running Grails application
| Error Server failed to start: org.apache.catalina.deploy.ContextResource (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.ClassNotFoundException: org.apache.catalina.deploy.ContextResource
	at org.grails.plugins.tomcat.InlineExplodedTomcatServer.loadInstance(InlineExplodedTomcatServer.groovy:168)
	at org.grails.plugins.tomcat.InlineExplodedTomcatServer$_preStart_closure2.doCall(InlineExplodedTomcatServer.groovy:191)
	at org.grails.plugins.tomcat.InlineExplodedTomcatServer.preStart(InlineExplodedTomcatServer.groovy:182)
	at org.grails.plugins.tomcat.InlineExplodedTomcatServer.doStart(InlineExplodedTomcatServer.groovy:107)
	at org.grails.plugins.tomcat.TomcatServer.start(TomcatServer.groovy:146)
	at grails.web.container.EmbeddableServer$start.call(Unknown Source)
	at _GrailsRun$_run_closure1.doCall(_GrailsRun.groovy:60)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at RunApp$_run_closure1.doCall(RunApp:33)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
| Error Server failed to start: org.apache.catalina.deploy.ContextResource

**Comment by burtbeckwith** [comment]
fixed in 8.0.33 and 9.0.0.M4.1
